[features]
seeds = false
skip-lint = false
[programs.localnet]
calculator = "AvDAVR91oPv5fb2dBMkDEwpeSiSNtyekijcRG9UjPLYt"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/beliv/ackee/calculator/a4vS79PVCnQ5nN3AkPuAZDDUSpMtyvV5HR292mqTX6U.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
